### PR TITLE
[BUGFIX] Make PHP-CS-Fixer >= 3.66 compatible with PHPUnit 9.x

### PR DESCRIPTION
**Pull request by oliverklee**
@see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/8337

### CODE REVIEW

**Comment by oliverklee** [comment]
After this has gotten a +1, I'll need to merge this change into the PHP-CS-Fixer update PR at #1534.

**Comment by oliverklee** [comment]
See this in action with the PHP-CS-Fixer update: https://github.com/oliverklee/ext-onetimeaccount/pull/1053

**Review by linxpinx — APPROVED** [review]
looks good

**Comment by oliverklee** [comment]
Thanks! Integrated into #1533 and merged.

**Pull request closed without merging**
